### ISSUE TITLE
The exporter always give AttributeError

### ISSUE THREAD

**Issue by Savasw** [aylei/aliyun-exporter#17]
When followed the steps given in read me using pip installed package or using docker image/docker-compose, the exporter always errors out,

```Traceback (most recent call last):
  File "/usr/local/bin/aliyun-exporter", line 11, in <module>
    load_entry_point('aliyun-exporter', 'console_scripts', 'aliyun-exporter')()
  File "/usr/src/app/aliyun_exporter/__init__.py", line 39, in main
    REGISTRY.register(collector)
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/registry.py", line 24, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/registry.py", line 65, in _get_names
    for suffix in type_suffixes.get(metric.type, ['']):
AttributeError: 'NoneType' object has no attribute 'type'
```

**Comment by SQGE** [comment]
docker-compose 启动也发生同样错误

**Comment by SQGE** [comment]
我使用docker-compose启动，aliyun-exporter发生同样的错误
