### ISSUE TITLE
TypeError: an integer is required

### ISSUE THREAD

**Issue by gecailong** [aylei/aliyun-exporter#6]
when i start running it,it threw one error to me;
error  log:
# ./aliyun-exporter --port 9555 --config-file ./aliyun-exporter.yml
INFO:root:Start exporter, listen on 9555
Traceback (most recent call last):
  File "./aliyun-exporter", line 11, in <module>
    sys.exit(main())
  File "/usr/local/python3/lib/python3.6/site-packages/aliyun_exporter/__init__.py", line 40, in main
    start_http_server(args.port)
  File "/usr/local/python3/lib/python3.6/site-packages/prometheus_client/exposition.py", line 181, in start_http_server
    httpd = _ThreadingSimpleServer((addr, port), CustomMetricsHandler)
  File "/usr/local/python3/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/usr/local/python3/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/python3/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
TypeError: an integer is required (got type str)

promblem:
Is there something wrong with my use? or how  can i use it? my QQ645158469,

**Comment by aylei** [comment]
Thanks! this is a bug of the exporter I suppose, I will fix it and release a new version😁

**Comment by aylei** [comment]
Hi @gecailong, I've fixed this bug and release 0.2.2, upgrading the package will fix your problem!
